### ISSUE TITLE
Testrun Unedfined Steps that actually run BUG

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-issue-tracker#135]
I have the following testrun 
![image](https://user-images.githubusercontent.com/22622247/40484648-ba22c0a0-5f32-11e8-941e-14698d587839.png)

with the following error on the stack trace

```
time: 138.95531 seconds

java.lang.RuntimeException: Unable to perform click on:By.xpath: //android.support.v7.widget.RecyclerView[@resource-id='com.olx.ssa.za:id/dialog_select_list']/android.widget.RelativeLayout/android.widget.TextView[@resource-id='com.olx.ssa.za:id/category_name' and @text='Property']
 Exception Details:org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //android.support.v7.widget.RecyclerView[@resource-id='com.olx.ssa.za:id/dialog_select_list']/android.widget.RelativeLayout/android.widget.TextView[@resource-id='com.olx.ssa.za:id/category_name' and @text='Property'] (tried for 10 second(s) with 500 MILLISECONDS interval)
	at com.olx.automation.android.driver.AppiumHelper.clickElementBy(AppiumHelper.java:630)
	at com.olx.automation.android.pages.actions.FilterPageActions.selectFilterCategory(FilterPageActions.java:664)
	at com.olx.automation.android.pages.actions.FilterPageActions.clickCategoryOnFilter(FilterPageActions.java:620)
	at com.olx.automation.android.java.stepDefinitions.FilterDefinitions.theUserWishesToApplyCategoryFilter(FilterDefinitions.java:38)
	at ✽.And the user wishes to apply "houses_for_rent" category filter(features/Android/0400_Filter.feature:55)

stdout:
Given the user opens app....................................................passed
And the user bypass the onboarding as "user"................................passed
Given the user is on "home" screen..........................................passed
When the user search ads using a "house rent" keyword.......................passed
And the user should see "listing-search" screen.............................passed
And the user wishes to "see-filter-page"....................................passed
And the user wishes to apply "houses_for_rent" category filter..............failed
And the user apply selected filters.........................................skipped
Then the user should see "listing-search" screen............................skipped
And verify filters "houses_for_rent" applied................................skipped

StackTrace:
java.lang.RuntimeException: Unable to perform click on:By.xpath: //android.support.v7.widget.RecyclerView[@resource-id='com.olx.ssa.za:id/dialog_select_list']/android.widget.RelativeLayout/android.widget.TextView[@resource-id='com.olx.ssa.za:id/category_name' and @text='Property']
 Exception Details:org.openqa.selenium.TimeoutException: Expected condition failed: waiting for visibility of element located by By.xpath: //android.support.v7.widget.RecyclerView[@resource-id='com.olx.ssa.za:id/dialog_select_list']/android.widget.RelativeLayout/android.widget.TextView[@resource-id='com.olx.ssa.za:id/category_name' and @text='Property'] (tried for 10 second(s) with 500 MILLISECONDS interval)
	at com.olx.automation.android.driver.AppiumHelper.clickElementBy(AppiumHelper.java:630)
	at com.olx.automation.android.pages.actions.FilterPageActions.selectFilterCategory(FilterPageActions.java:664)
	at com.olx.automation.android.pages.actions.FilterPageActions.clickCategoryOnFilter(FilterPageActions.java:620)
	at com.olx.automation.android.java.stepDefinitions.FilterDefinitions.theUserWishesToApplyCategoryFilter(FilterDefinitions.java:38)
	at ✽.And the user wishes to apply "houses_for_rent" category filter(features/Android/0400_Filter.feature:55)
````

and the following situation wich according to the previous information is not good.

![image](https://user-images.githubusercontent.com/22622247/40484675-d38951ee-5f32-11e8-84a9-6cb63a510e8c.png)

**Comment by FatimaEzzahraIdrissi** [comment]
Hello,
Actually, we don't report step statuses when pushing results back to Hiptest. We have a planned Trello card which aims to report test steps that failed: [https://trello.com/c/31jCi79E/310-report-test-steps-that-failed](https://trello.com/c/31jCi79E/310-report-test-steps-that-failed) you can vote for it.
Regards,
Fatima
